[package]
name = "shards-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "2.1", features = ["postgres", "chrono"] }
diesel-async = { version = "0.4", features = ["postgres", "tokio"] }
chrono = "0.4"
tokio = { version = "1.0", features = ["full"] }