services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PSWD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    command: ["postgres", "-c", "log-statement=all"]
  redis:
    image: redis:latest
  app:
    build: .
    environment:
      - DATABASE_URL=postgres://${POSTGRES_DB_USER}:${POSTGRES_DB_PSWD}@postgres/${POSTGRES_DB_NAME}
    ports:
      - "8000:8000"
    volumes:
      - ./:/app/